baseURL = 'http://y0anfa.github.io/'
languageCode = 'en-us'
title = 'Yoan Faure'
theme = 'PaperMod'

[params.profileMode]
enabled = true
subtitle = "Security Engineer"
imageUrl = "images/profile.png"
imageTitle = "profile picture"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "Resume"
url = "/resume"

[[params.profileMode.buttons]]
name = "blog"
url = "/blog"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/yoan-faure/"

[[params.socialIcons]]
name = "email"
url = "mailto:yoanfaure@hotmail.fr"